#!/usr/bin/env sh

# Run typecheck
echo "Running typecheck..."
npx tsc --noEmit || exit 1

# Run eslint
echo "Running eslint..."
npx eslint . || exit 1

# Run prettier
echo "Running prettier check..."
npx prettier --check . || exit 1

exit 0
